//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Bordfodbold_System.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int id { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage = "Name required!")]
        public string name { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password required!")]
        public string password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
